/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Axiom Math
-/
module

public import Mathlib.NumberTheory.Bertrand
public import Mathlib.RingTheory.Ideal.Height
public import BrowningSawin.Attr
public import BrowningSawin.Notation

/-!
# External inputs already formalized in Mathlib

Two of the seven statements the source defers to the literature are already formalized in Mathlib,
so they are *not* assumptions of this development: Bertrand's postulate is
`Nat.exists_prime_lt_and_le_two_mul`, and Krull's height theorem is
`Ideal.height_le_card_of_mem_minimalPrimes_span_finset`. Each appears below as a theorem in the
shape the source uses it, proved from the Mathlib result.

The remaining five are genuinely assumed: see `BrowningSawin.Cited`, where each is a `Prop` that a
result resting on it carries as an explicit hypothesis.

## Main results

* `BrowningSawin.exists_prime_lt_and_le_two_mul`: Bertrand's postulate — for `m ≥ 1` there is a
  prime `q` with `m < q ≤ 2m`.
* `BrowningSawin.height_le_card_of_mem_minimalPrimes_span_range`: Krull's height theorem — over a
  Noetherian ring, a minimal prime over an ideal generated by `j` elements has height at most `j`.
-/

@[expose] public section

namespace BrowningSawin

open MvPolynomial

/-! ## Bertrand's postulate -/

/-- **Bertrand's postulate.** For every integer `m ≥ 1` there is a prime `q` with `m < q ≤ 2m`.

Cited by the source (Erdős, *Beweis eines Satzes von Tschebyschef*, 1932), and already formalized
in Mathlib as `Nat.exists_prime_lt_and_le_two_mul`; it is therefore a theorem of this development
rather than an assumption. -/
@[browning_sawin "lem_bertrand"]
theorem exists_prime_lt_and_le_two_mul {m : ℕ} (hm : 1 ≤ m) :
    ∃ q : ℕ, q.Prime ∧ m < q ∧ q ≤ 2 * m :=
  Nat.exists_prime_lt_and_le_two_mul m (by omega)

/-! ## Krull's height theorem -/

/-- **Krull's height theorem.** Over a Noetherian ring, every minimal prime over an ideal generated
by a family `a₁, …, a_j` has height at most `j`.

Cited by the source (Krull's *Höhensatz*: Krull, 1928; see Matsumura, *Commutative Ring Theory*,
1986, §13, which carries no separate numbering for the source's phrasing), and already formalized
in Mathlib as `Ideal.height_le_card_of_mem_minimalPrimes_span_finset`; it is therefore a theorem of
this development rather than an assumption. The family is indexed by an arbitrary finite type, `j`
being its cardinality. -/
@[browning_sawin "lem_krull_height"]
theorem height_le_card_of_mem_minimalPrimes_span_range {R : Type*} [CommRing R] [IsNoetherianRing R]
    {ι : Type*} [Fintype ι] (a : ι → R) {p : Ideal R}
    (hp : p ∈ (Ideal.span (Set.range a)).minimalPrimes) : p.height ≤ Fintype.card ι := by
  classical
  have hspan : (Finset.image a Finset.univ : Finset R) = (Set.range a : Set R) := by
    simp [Finset.coe_image]
  have h := Ideal.height_le_card_of_mem_minimalPrimes_span_finset
    (s := Finset.image a Finset.univ) (hspan ▸ hp)
  exact h.trans (by exact_mod_cast Finset.card_image_le.trans_eq (Finset.card_univ))

end BrowningSawin
